# This is a basic workflow to help you get started with Actions

name: Serverless Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    
    - name: Set up Node
      uses: actions/setup-node@v2.1.1
      with:
        node-version: 12

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Update with your python version

    - name: Serverless Deploy
      uses: dhollerbach/github-action-serverless-with-python-requirements@master
      with:
        args: '--stage dev'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
    
#     - name: serverless deploy
#       uses: serverless/github-action@master
#       with:
#         args: deploy
#       env:
# #         SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
#         # or if using AWS creds directly
#         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
